### ISSUE TITLE
No symbol "dlopen" in current context

### ISSUE THREAD

**Issue by twestley** [robertknight/Qt-Inspector#11]
From gdb.log:

`call dlopen(\"/home/terry.westley/usr/Qt-Inspector-master/build/lib/libQtInspector.so\",2)\n"
&"No symbol \"dlopen\" in current context.\n"`

Is this something wrong with the way I'm building my application under test?

**Comment by robertknight** [comment]
That function should be coming from the `libdl` library. Can you post the rest of gdb.log here and also details of your distribution?

**Comment by twestley** [comment]
CentOS 7, specifically:
```
$ cat /proc/version 
Linux version 3.10.0-327.3.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Wed Dec 9 14:09:15 UTC 2015
```
gcc-6.1.0 is in my path for compiling code

gdb.log attached: [gdb.log.txt](https://github.com/robertknight/Qt-Inspector/files/503281/gdb.log.txt)

**Comment by twestley** [comment]
One of my coworkers has successfully built qtinspector and I'm using his version now.

**Comment by mdeweerd** [comment]
Adding `gdbStream << "sharedlibrary libdl\n"; helps with this issue.
`
