### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by postadelmaga** [robertknight/Qt-Inspector#16]
I tried run:
```
qtinspector okular
qtinspector dolphin
```
But nothing happens, maybe it is not compatible with QT5 ?

Anyway ...
My aim is to change the background/font color of a close source QT4 app (TimeDoctor) because It is not usable with Breeze Dark.
if I try run:
`qtinspector timedoctorpro
`
The Timedoctor is executed but nothing else happens, I expect the Widget Inspector to start as well ... at least this is what I understood but maybe I am wrong ...

**Comment by robertknight** [comment]
> But nothing happens, maybe it is not compatible with QT5 ?

I can't recall whether I ever got this working with Qt 5 or not. It was [building against Qt 5](https://github.com/robertknight/Qt-Inspector/commit/925f64dbc567c66971bc32291a8fdb44839a7cf0) at one point but I can't recall if it ever worked.

> The Timedoctor is executed but nothing else happens, I expect the Widget Inspector to start as well ... at least this is what I understood but maybe I am wrong ...

That usage is correct. Are there any log messages displayed by the tool on startup? If the Widget Inspector never appears it might mean that connection to the "server" library running inside the app never completes. See https://github.com/robertknight/Qt-Inspector/blob/cce98a114ef9c8b3fb120d412ddba8bad834f64c/PreloadInjector.cpp#L54 . I'm afraid you'll have to do some debugging to find out what's going on.
