### ISSUE TITLE
Bring this project back!

### ISSUE THREAD

**Issue by zethon** [robertknight/Qt-Inspector#25]
I need this in my life.

If I didn't have a ton of other projects I was already working on, I'd fork this and try to bring it back myself.

Please!

**Comment by robertknight** [comment]
I do not expect to be doing any maintenance work on this project myself any time soon, but I will try to test and review contributions from others.

**Comment by torokati44** [comment]
As an alternative, you might be interested in this other, similar project: https://github.com/KDAB/GammaRay

**Comment by robertknight** [comment]
I have never used it, but indeed GammaRay is the most professionally supported alternative that I know of. I'm closing this issue as I've clarified the current maintenance status/plans.
