### ISSUE TITLE
CMakeLists.txt

### ISSUE THREAD

**Issue by StachuJemiola** [robertknight/Qt-Inspector#6]
I think there should be "option(USE_QT5 "QT5" OFF)" instead of "option(USE_QT5 OFF)" in CMakeLists.txt.

**Comment by robertknight** [comment]
Indeed, according to [the documentation](https://cmake.org/cmake/help/v3.0/command/option.html) the syntax is `option(VARIABLE <description> <initial value>)` so the second argument should be something like 'Build with Qt 5'. I don't have a system set up to test just at the moment, if you wouldn't mind creating a pull request I'd be happy to accept.

**Comment by romanzoller** [comment]
It looks like this was fixed by PR #7
