### ISSUE TITLE
cmake src

### ISSUE THREAD

**Issue by roydekleijn** [robertknight/Qt-Inspector#8]
Hello,

I'm getting the following error:

MacBook-Pro:projects user$ cmake Qt-Inspector/
Building with Qt 4. Enable the USE_QT5 option to build with Qt 5
-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PROTOBUF_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /Users/user/develop/projects/Qt-Inspector/lib
PROTOBUF_LIBRARY (ADVANCED)
    linked by target "QtInspector" in directory /Users/user/develop/projects/Qt-Inspector/lib

-- Configuring incomplete, errors occurred!
See also "/Users/user/develop/projects/Qt-Inspector/CMakeFiles/CMakeOutput.log".
See also "/Users/user/develop/projects/Qt-Inspector/CMakeFiles/CMakeError.log".

What can I do to resolve this issue ?

Thanks,
Roy de Kleijn

**Comment by robertknight** [comment]
Hello Roy,

You'll need to install the protocol buffers library. I believe the easiest way to do this on Mac would be to use Homebrew via `brew install protobuf`. See http://brewformulas.org/Protobuf

**Comment by roydekleijn** [comment]
Thabks for your answer,

However I now see the following error..

MacBook-Pro:Qt-Inspector user$ cmake .
CMake Error at CMakeLists.txt:14 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!

**Comment by roydekleijn** [comment]
thanks for your answer, where can I find ./qtinspector ?
