### ISSUE TITLE
qtinspector failed to start because it could not load the Qt platform plugin 'cocoa'

### ISSUE THREAD

**Issue by dspreadbury** [robertknight/Qt-Inspector#9]
I'm trying to run Qt-Inspector on OS X 10.11 El Capitan. I have Qt 5.5.1, which cmake (which I think I installed via homebrew a while ago) seems able to find OK. I have installed Google Protocol Buffers by way of `brew install protobuf`, after cmake first complained it couldn't find it.

After `cmake -DUSE_QT5=on` seemed to get me a properly configured build, I did `make -j2` as recommended in the readme, and the build completed successfully.

However, when I try to run Qt-Inspector and attach it to a running process, I get the output:

```
This application failed to start because it could not find or load the Qt platform plugin "cocoa".

Reinstalling the application may fix this problem.
Abort trap: 6
```

I have `~/qt5/plugins/platforms/libqcocoa.dylib` and have tried copying libqcocoa.dylib alongside the qtinspector executable, but that doesn't work.

Can you give me any hints as to how to get up and running?

Thanks!

**Comment by robertknight** [comment]
Hello @dspreadbury - I'm afraid I've not tried to set up Qt on OS X for a long time. My instinct here would be to find a way to trace the files that the program attempts to stat or open on startup and see where it looks for the 'libqcocoa.dylib' library.

**Comment by dspreadbury** [comment]
Using `fs_usage | grep qtinspector` I was able to see that it was looking inside a subfolder called `platforms` alongside the executable for the `libqcocoa.dylib` file. I was able to start the application once I put the dynamic library in that folder.

Thanks for your help, and for the very useful tool!

**Comment by torrtuga** [comment]
I am getting similar error and not able to run the deployed app because of the same errors.
Can you please have a look in this question?

**Comment by robertknight** [comment]
Hi @torrtuga - I'm afraid I'm short of time at the moment so you're going to have to figure this one out for yourself based on previous comments.

**Comment by torrtuga** [comment]
@robertknight Okay, whenever you get time please have a look in this forum thread : https://forum.qt.io/topic/82746/creating-dmg-for-qt-app-mac-osx
